config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :wiki_posts
  namespace :wiki_posts do
    get 'example'
  end
  namespace :welcome do
    get 'index'
    get 'about'
    get 'archive'
  end

  namespace :api do
    namespace :v1 do
      resources :wiki_posts, only: [:index]
    end
  end

  get '/about', to: redirect('/welcome/about')
  root 'welcome#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/wiki_post.rb
# frozen_string_literal: true

class WikiPost < ApplicationRecord
  has_one_attached :image
  has_one :wiki_post_record, dependent: :destroy
  after_save :create_wiki_post_record

  validates_format_of :title, with: /\A[a-zA-Z0-9\s.,!?:;'-]+\z/

  scope :contributors, -> { pluck(:author).uniq }

  private

  def create_wiki_post_record
    data = {
      id:,
      created_at:,
      updated_at:,
      title:,
      description:,
      author:
    }
    build_wiki_post_record(data:).save!
  end
end

app/models/wiki_post_record.rb
# frozen_string_literal: true

class WikiPostRecord < ApplicationRecord
  belongs_to :wiki_post
  validates :wiki_post, presence: true
end

app/controllers/api/v1/wiki_posts_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class WikiPostsController < ApplicationController
      include LoggingModule
      def index
        data = {}
        WikiPost.includes(:wiki_post_record).each do |post|
          data[post.id] = post.wiki_post_record.data
        end
        final = WikiPostSerializer.serialize(data)
        render json: final
      rescue StandardError => e
        render json: "Error: #{e.message}"
      end
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index; end

  def about
    @wiki_posts = WikiPost.all
  end
end

app/controllers/wiki_posts_controller.rb
# frozen_string_literal: true

class WikiPostsController < ApplicationController
  include LoggingModule
  before_action :set_wiki_post, only: %i[edit update destroy]

  # GET /wiki_posts or /wiki_posts.json
  def index
    @wiki_posts = WikiPost.all
    log_debug("WikiPosts Loaded - count: #{@wiki_posts.count}")
  end

  # GET /wiki_posts/1 or /wiki_posts/1.json
  def show
    log_info("WikiPost viewed: #{@wiki_post.title}")
  end

  def example; end

  # GET /wiki_posts/new
  def new
    @wiki_post = WikiPost.new
  end

  # GET /wiki_posts/1/edit
  def edit; end

  # POST /wiki_posts or /wiki_posts.json
  def create
    @wiki_post = WikiPost.new(wiki_post_params)

    respond_to do |format|
      if @wiki_post.save
        format.html { redirect_to wiki_post_url(@wiki_post), notice: 'Wiki post was successfully created.' }
        format.json { render :show, status: :created, location: @wiki_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wiki_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wiki_posts/1 or /wiki_posts/1.json
  def update
    respond_to do |format|
      if @wiki_post.update(wiki_post_params)
        format.html { redirect_to wiki_post_url(@wiki_post), notice: 'Wiki post was successfully updated.' }
        format.json { render :show, status: :ok, location: @wiki_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wiki_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wiki_posts/1 or /wiki_posts/1.json
  def destroy
    @wiki_post.destroy

    respond_to do |format|
      format.html { redirect_to wiki_posts_url, notice: 'Wiki post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_wiki_post
    @wiki_post = WikiPost.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    log_error("WikiPost not found - ID: #{params[:id]}")
    redirect_to wiki_posts_path, alert: 'WikiPost not found.'
  end

  # Only allow a list of trusted parameters through.
  def wiki_post_params
    params.fetch(:wiki_post, {}).permit(:title, :description, :author, :image)
  end
end

app/helpers/api/v1/wiki_post_helper.rb
# frozen_string_literal: true

module Api
  module V1
    module WikiPostHelper
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/helpers/wiki_posts_helper.rb
# frozen_string_literal: true

module WikiPostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= javascript_importmap_tags %>
    <%= turbo_include_tags %>


    <title>WikiApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>
`

app/views/welcome/about.html.erb
<h1>Wiki</h1>
<h2>Site contributors: </h2>
<ul>
<% @wiki_posts.contributors.compact.each do |contributor| %>
  <li><%= contributor.titleize %></li>
  <% end %>
</ul>

app/views/welcome/index.html.erb
<h1><%="#{ENV['TITLE']}'s WikiApp" %></h1>
<h2><%= link_to 'View Posts', wiki_posts_path %></h2>
<h2><%= link_to "About", welcome_about_path%></h2>

app/views/wiki_posts/_form.html.erb
<%= form_with(model: wiki_post) do |form| %>
  <% if wiki_post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(wiki_post.errors.count, "error") %> prohibited this wiki_post from being saved:</h2>

      <ul>
        <% wiki_post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/wiki_posts/_wiki_post.html.erb
<div id="<%= dom_id wiki_post %>">
</div>

app/views/wiki_posts/edit.html.erb
<h1>Editing wiki post</h1>
<%= form_with model: @wiki_post, local: true do |form| %>

  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.submit "Edit" %>
  </div>
<% end %>
<br>

<div>
  <%= link_to "Show this wiki post", @wiki_post %> |
  <%= link_to "Back to wiki posts", wiki_posts_path %>
</div>

app/views/wiki_posts/example.html.erb
<h1 class="title" > Wiki Page Title </h1>

<p class="description">  Wiki Page Body</p>

<div class="meta">
  <span class="author"> Wiki Page Author </span>
  <span class="creation"> Wiki Page Creation Date </span>
  <span class="update"> Wiki Last Update Date </span>

</div>

app/views/wiki_posts/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Wiki Posts</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Created at</th>
      <th>Updated at</th>
    </tr>
  </thead>
  <tbody>
    <% @wiki_posts.each do |post| %>
      <tr>
        <td><%= link_to post.title, wiki_post_path(post) %></td>
        <td><%= post.created_at.strftime("%m-%d-%Y") %></td>
        <td><%= post.updated_at.strftime("%m-%d-%Y") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2>Site contributors: </h2>
<ul>
  <% @wiki_posts.contributors.each do |contributor| %>
    <li><%= contributor.titleize %></li>
  <% end %>
</ul>

<%= link_to "New wiki post", new_wiki_post_path %>

app/views/wiki_posts/new.html.erb
<h1>New wiki post</h1>
<%= form_with model: @wiki_post, local: true do |form| %>

  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <div >
      <%= form.label :description%><br>
      <%= form.text_field :description %>
    </div>
    <div >
      <%= form.label :author%><br>
      <%= form.text_field :author %>
    </div>
    <div class="field">
      <%= form.label :image %>
      <%= form.file_field :image %>
    </div>
  </div>
  <div>
    <%= form.submit "Create!" %>
  </div>
<% end %>
<br>
<div>
  <%= link_to "Back to wiki posts", wiki_posts_path %>
</div>

app/views/wiki_posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @wiki_post %>

<h1><%= @wiki_post.title.titleize %></h1>
<p>Created on <%= @wiki_post.created_at.strftime('%B %d, %Y') %></p>
<p>Description: <%= @wiki_post.description %></p>
<p>Author: <%=@wiki_post.author.titleize %><p>

<% if @wiki_post.image.attached? %>
  <%= image_tag @wiki_post.image %>
<% end %>


<div>
  <%= link_to "Edit this wiki post", edit_wiki_post_path(@wiki_post) %> |
  <%= link_to "Back to wiki posts", wiki_posts_path %>

  <%= button_to "Delete", @wiki_post, method: :delete, form: { data: { turbo_confirm: "Are you sure you want to delete #{@wiki_post.title}?" } } %>
</div>